### ISSUE TITLE
[BUG] Nested mixed required input output wrong joi 

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acr-lfr/generate-it#73]
**Describe the bug**
Wrong joi validation output

**To Reproduce**
This nested object as an input model for post
```
type: object
required:
  - editable
properties:
  editable:
    type: object
    required:
      - text
    properties:
      channel:
        type: object
        required:
          - slug
          - name
        properties:
          slug:
            type: string
            description: The slug of the channel
          name:
            type: string
            description: The name of the channel
          isDefault:
            type: boolean
            description: Is this channel a default channel
      text:
        type: string
        description: The text of the item, this includes URL and user added text
```

**Expected behavior**
It should output:
```
  itemPost: {
    body: Joi.object({
      editable: Joi.object({
        channel: Joi.object({
          slug: Joi.string().allow('').required(),
          name: Joi.string().allow('').required(),
          isDefault: Joi.boolean(),
        }),
        text: Joi.string().allow('').required(),
      }).required(),
    }),
  },
```
It instead outputs:
```
  itemPost: {
    body: Joi.object({
      editable: Joi.object({
        channel: Joi.object({
          slug: Joi.string().allow(''),
          name: Joi.string().allow(''),
          isDefault: Joi.boolean(),
        }).required(),
        text: Joi.string().allow(''),
      }).required(),
    }),
  },
```
Note the actual output for body.editable which is correct, but the required elements within are incorrect
