### ISSUE TITLE
[BUG] default values on query param array not working

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acr-lfr/generate-it#83]
Example query parameter input:
```
in: query
name: getStage
required: false
type: array
items:
  type: string
  enum:
    - stageGet
    - stageGot
default:
  - stageGet
  - stageGot
```

The expected output would be that the Joi validator sets the default value to ['stageGet','stageGot']

The actual result is that no default option is produced
